
package interfaces;

import java.awt.Frame;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import poo.pl2.Inmueble;
import poo.pl2.Reserva;
import poo.pl2.UtilReservas;
import poo.pl2.UtilUsuarios;

/**
 *
 * @author Esthe
 */
public class ConsultarReserva extends javax.swing.JDialog {

    private static final long serialVersionUID = 1L;

    private Reserva resAux;
    Frame principal;
    /**
     * Creates new form ConsultarReserva
     * @param parent
     * @param modal
     */
    public ConsultarReserva(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        this.setVisible(true);
    }
    
    /**
     *
     * @param parent
     * @param modal
     * @param reserva
     */
    public ConsultarReserva(java.awt.Frame parent, boolean modal, Reserva reserva){
        super(parent, modal);
        initComponents();
        
        presenta(reserva);
        desactivar();
        resAux = reserva;
        
        if(UtilUsuarios.getAnfit()==null && UtilUsuarios.getPartic()==null){
            //es admin
            buttonCancelar.setVisible(false);
            buttonCalificar.setVisible(false);
            
        }
        if(UtilUsuarios.getAnfit()!=null){
            //es anfitrion
            buttonCancelar.setVisible(true);
            buttonCalificar.setVisible(false);
            
        }
        if(UtilUsuarios.getPartic()!=null){
            //es particular
            buttonCancelar.setVisible(true);
            buttonCalificar.setVisible(true);
        }
        
        this.setVisible(true);
    }
    
    /**
     *rellena los fields y spins del panel con los datos de la reserva
     * @param reserva
     */
    public void presenta(Reserva reserva){
        Inmueble inm = reserva.getInmuebleDatos();
        labelTitulo.setText(inm.getTitulo());
        labelCiudad.setText(inm.getDireccion().getCiudad());
        labelAnfit.setText(inm.getAnfitrion().getCorreoElectronico());
        labelPartic.setText(reserva.getClienteParticular().getCorreoElectronico());
        setLabelImagen(inm.getImagen());
        spinFechaReserva.setValue(reserva.getFechaReserva());
        spinFechaEntrada.setValue(reserva.getFechaEntrada());
        spinFechaSalida.setValue(reserva.getFechaSalida());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelImagen = new javax.swing.JLabel();
        labelTitulo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelCiudad = new javax.swing.JLabel();
        labelAnfit = new javax.swing.JLabel();
        labelPartic = new javax.swing.JLabel();
        spinFechaReserva = new javax.swing.JSpinner();
        spinFechaEntrada = new javax.swing.JSpinner();
        spinFechaSalida = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        buttonCancelar = new javax.swing.JButton();
        buttonCalificar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Fecha de Reserva");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Anfitrion");

        labelImagen.setToolTipText("imagen");

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelTitulo.setToolTipText("titulo");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("INMUEBLE");

        jLabel4.setText("Particular");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Ciudad");

        spinFechaReserva.setModel(new javax.swing.SpinnerDateModel());

        spinFechaEntrada.setModel(new javax.swing.SpinnerDateModel());

        spinFechaSalida.setModel(new javax.swing.SpinnerDateModel());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Fecha de Entrada");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Fecha de Salida");

        buttonCancelar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonCancelar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Esthe\\OneDrive - Universidad de Alcala\\GISI\\1curso\\Programación\\PL2\\imagenes\\reservaPequeña.png")); // NOI18N
        buttonCancelar.setText("Cancelar Reserva");
        buttonCancelar.setToolTipText("");
        buttonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarActionPerformed(evt);
            }
        });

        buttonCalificar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonCalificar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Esthe\\OneDrive - Universidad de Alcala\\GISI\\1curso\\Programación\\PL2\\imagenes\\inmueblePequeño.png")); // NOI18N
        buttonCalificar.setText("Calificar Inmueble");
        buttonCalificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCalificarActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Esthe\\OneDrive - Universidad de Alcala\\GISI\\1curso\\Programación\\PL2\\imagenes\\LogoPequeño.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(126, 126, 126)
                                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelPartic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(labelCiudad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(labelAnfit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(spinFechaReserva)
                                    .addComponent(spinFechaEntrada)
                                    .addComponent(spinFechaSalida)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(buttonCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonCalificar)))
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(22, 22, 22))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(58, 58, 58)
                    .addComponent(jLabel3)
                    .addContainerGap(438, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(labelImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(labelCiudad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(labelAnfit))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(labelPartic))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(spinFechaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinFechaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCancelar)
                    .addComponent(buttonCalificar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addComponent(jLabel3)
                    .addContainerGap(393, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelarActionPerformed
        // TODO add your handling code here:
        if(UtilReservas.eliminarReserva(resAux)){
            JOptionPane.showMessageDialog(principal, "Reserva cancelada.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            borrar();
            dispose();
        }else{
            JOptionPane.showMessageDialog(principal, "Error al cancelar la reserva.", "Mensaje", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonCancelarActionPerformed

    private void buttonCalificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCalificarActionPerformed
        // TODO add your handling code here:
        Calificar c = new Calificar (principal, true, resAux,UtilUsuarios.getPartic()); 
    }//GEN-LAST:event_buttonCalificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ConsultarReserva dialog = new ConsultarReserva(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    

    /**
     *vacía los fields y pone en los spins la fecha de hoy
     */
    public void borrar(){
        labelAnfit.setText("");
        labelCiudad.setText("");
        labelImagen.setText("");
        labelPartic.setText("");
        labelTitulo.setText("");
        Date hoy = new Date();
        spinFechaEntrada.setValue(hoy);
        spinFechaSalida.setValue(hoy);
        spinFechaReserva.setValue(hoy);
    }
    
    /**
     *permite la modificación, edición y uso de los 3 spins
     */
    public void activar(){
        spinFechaEntrada.setEnabled(true);
        spinFechaSalida.setEnabled(true);
        spinFechaReserva.setEnabled(true);
    }
    
    /**
     *desactiva la edición de los 3 spins de las fechas
     */
    public void desactivar(){
        spinFechaEntrada.setEnabled(false);
        spinFechaSalida.setEnabled(false);
        spinFechaReserva.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCalificar;
    private javax.swing.JButton buttonCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel labelAnfit;
    private javax.swing.JLabel labelCiudad;
    private javax.swing.JLabel labelImagen;
    private javax.swing.JLabel labelPartic;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JSpinner spinFechaEntrada;
    private javax.swing.JSpinner spinFechaReserva;
    private javax.swing.JSpinner spinFechaSalida;
    // End of variables declaration//GEN-END:variables

    //Getters & Setters
    public String getLabelTitulo(){
        return labelTitulo.getText();
    }
    
    public void setLabelTitulo(String txt){
        labelTitulo.setText(txt);
    }
    
    public String getLabelCiudad(){
        return labelCiudad.getText();
    }
    
    public void setLabelCiudad(String txt){
        labelCiudad.setText(txt);
    }
    
    public String getLabelAnfit(){
        return labelAnfit.getText();
    }
    
    public void setLabelAnfit(String txt){
        labelAnfit.setText(txt);
    }
    
    public String getLabelPartic(){
        return labelPartic.getText();
    }
    
    public void setLabelPartic(String txt){
        labelPartic.setText(txt);
    }
    
    public String getLabelImagen() {
        return labelImagen.getText();
    }

    public void setLabelImagen(String rutaImagen) {
        ImageIcon imagen = new ImageIcon(rutaImagen);
        //Se redimensiona
        ImageIcon imgRedimensionada = new ImageIcon(imagen.getImage().getScaledInstance(labelImagen.getWidth(), labelImagen.getHeight(), 1));
        labelImagen.setIcon(imgRedimensionada);
    }
    
    public Date getFechaReserva() {
        return (Date) spinFechaReserva.getValue();
    }

    public void setFechaReserva(Date fechaReserva) {
        this.spinFechaReserva.setValue(fechaReserva);
    }
    
    public Date getFechaEntrada() {
        return (Date) spinFechaEntrada.getValue();
    }

    public void setFechaEntrada(Date fechaEntrada) {
        this.spinFechaEntrada.setValue(fechaEntrada);
    }
    
    public Date getFechaSalida() {
        return (Date) spinFechaSalida.getValue();
    }

    public void setFechaSalida(Date fechaSalida) {
        this.spinFechaSalida.setValue(fechaSalida);
    }
}

