package interfaces;

import java.awt.BorderLayout;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Arrays;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import poo.pl2.Anfitrion;
import poo.pl2.UtilUsuarios;

public class InicioAnfitrion extends javax.swing.JFrame {
    
    /**
     *
     */
    public InicioAnfitrion() {
        initComponents();
        Anfitrion anfit = UtilUsuarios.getAnfit();
        if(UtilUsuarios.esSuperAnfitrion(anfit)){
            labelSuper.setVisible(true);
        }else{
            labelSuper.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        herramientas3 = new javax.swing.JToolBar();
        jLabel4 = new javax.swing.JLabel();
        buttonCrearInmueble = new javax.swing.JButton();
        buttonConsultarInm = new javax.swing.JButton();
        buttonModifDatos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelPrincipal = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        labelSuper = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        herramientas3.setRollover(true);

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(24, 40, 134));
        jLabel4.setText("ANFITRION");
        herramientas3.add(jLabel4);

        buttonCrearInmueble.setIcon(new javax.swing.ImageIcon("C:\\Users\\Esthe\\OneDrive - Universidad de Alcala\\GISI\\1curso\\Programación\\PL2\\imagenes\\masPequeño.png")); // NOI18N
        buttonCrearInmueble.setToolTipText("Crear Inmueble");
        buttonCrearInmueble.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonCrearInmueble.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonCrearInmueble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCrearInmuebleActionPerformed(evt);
            }
        });
        herramientas3.add(buttonCrearInmueble);

        buttonConsultarInm.setIcon(new javax.swing.ImageIcon("C:\\Users\\Esthe\\OneDrive - Universidad de Alcala\\GISI\\1curso\\Programación\\PL2\\imagenes\\inmueblePequeño.png")); // NOI18N
        buttonConsultarInm.setToolTipText("Consultar Inmuebles");
        buttonConsultarInm.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonConsultarInm.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonConsultarInm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConsultarInmActionPerformed(evt);
            }
        });
        herramientas3.add(buttonConsultarInm);

        buttonModifDatos.setIcon(new javax.swing.ImageIcon("C:\\Users\\Esthe\\OneDrive - Universidad de Alcala\\GISI\\1curso\\Programación\\PL2\\imagenes\\usuarioPequeño.png")); // NOI18N
        buttonModifDatos.setToolTipText("Modificar Datos");
        buttonModifDatos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonModifDatos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonModifDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonModifDatosActionPerformed(evt);
            }
        });
        herramientas3.add(buttonModifDatos);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Esthe\\OneDrive - Universidad de Alcala\\GISI\\1curso\\Programación\\PL2\\imagenes\\LogoJavaBnB.png")); // NOI18N

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(jLabel9)
                .addContainerGap(1725, Short.MAX_VALUE))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(jLabel9)
                .addContainerGap(519, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(panelPrincipal);

        labelSuper.setIcon(new javax.swing.ImageIcon("C:\\Users\\Esthe\\OneDrive - Universidad de Alcala\\GISI\\1curso\\Programación\\PL2\\imagenes\\estrella.png")); // NOI18N

        jLabel19.setIcon(new javax.swing.ImageIcon("C:\\Users\\Esthe\\OneDrive - Universidad de Alcala\\GISI\\1curso\\Programación\\PL2\\imagenes\\LogoPequeño.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(herramientas3, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelSuper, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 998, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelSuper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(17, 17, 17))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(herramientas3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonModifDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonModifDatosActionPerformed
        // TODO add your handling code here:
        DatosAnfitrion datosAnfit = new DatosAnfitrion();
        datosAnfit.setSize(400,310);
        datosAnfit.setLocation(0,0);
        
        Anfitrion anfit = UtilUsuarios.getAnfit();
        
        datosAnfit.setFieldNombre(anfit.getNombre());
        datosAnfit.setFieldDni(anfit.getDni());
        datosAnfit.setFieldTelefono(anfit.getTelefono());
        datosAnfit.setFieldCorreo(anfit.getCorreoElectronico());
        datosAnfit.setFieldClave(anfit.getClave());
        
        JButton buttonGuardar = new JButton("Guardar");
        buttonGuardar.setBounds(80, 385, 105, 35);
        
        panelPrincipal.removeAll();
        panelPrincipal.setLayout(new BorderLayout());
        panelPrincipal.add(datosAnfit, BorderLayout.CENTER);
        panelPrincipal.add(buttonGuardar,BorderLayout.SOUTH);
        panelPrincipal.revalidate();
        panelPrincipal.repaint();
        System.out.println(Arrays.toString(panelPrincipal.getComponents()));
        
        /**Botón guardar datos modificados
         * Creación del button y ActionListener
         */
        buttonGuardar.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            try{
                String nombre = datosAnfit.getFieldNombre();
                String dni = datosAnfit.getFieldDni();
                String telefono = datosAnfit.getFieldTelefono();
                String correo = datosAnfit.getFieldCorreo();
                String clave = datosAnfit.getFieldClave();

                Anfitrion anfitrion = UtilUsuarios.getAnfit();

                if(UtilUsuarios.modificarDatosAnfitrion(nombre, dni, telefono, correo, clave, anfitrion)){
                    JOptionPane.showMessageDialog(buttonGuardar, "Datos modificados.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                    datosAnfit.borrar();
                } else {
                    JOptionPane.showMessageDialog(panelPrincipal, "Error al modificar datos.", "Mensaje", JOptionPane.ERROR_MESSAGE);
                }
            }catch (HeadlessException exc) {
                JOptionPane.showMessageDialog(panelPrincipal, "Excepción al modificar datos.", "Mensaje", JOptionPane.ERROR_MESSAGE);
                System.out.println("Error: " + exc.toString());
            }
            catch (NullPointerException exc) {
                JOptionPane.showMessageDialog(panelPrincipal, "Excepción al modificar datos: Alguno de los campos es nulo.", "Mensaje", JOptionPane.ERROR_MESSAGE);
                System.out.println("Error: " + exc.toString());
            }
            }
        });//fin de button guardar
    }//GEN-LAST:event_buttonModifDatosActionPerformed

    private void buttonConsultarInmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConsultarInmActionPerformed
        // TODO add your handling code here:
        Anfitrion anfit = UtilUsuarios.getAnfit();
        ConsultarInmuebles c = new ConsultarInmuebles(this, true, anfit);
    }//GEN-LAST:event_buttonConsultarInmActionPerformed

    private void buttonCrearInmuebleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCrearInmuebleActionPerformed
        // TODO add your handling code here:
        CrearInmueble panelCrearInmueble = new CrearInmueble();
        panelCrearInmueble.setSize(1205, 655);
        panelCrearInmueble.setLocation(0,0);
        
        panelPrincipal.removeAll();
        panelPrincipal.add(panelCrearInmueble, BorderLayout.CENTER);
        panelPrincipal.revalidate();
        panelPrincipal.repaint();
        
    }//GEN-LAST:event_buttonCrearInmuebleActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioAnfitrion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioAnfitrion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioAnfitrion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioAnfitrion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioAnfitrion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonConsultarInm;
    private javax.swing.JButton buttonCrearInmueble;
    private javax.swing.JButton buttonModifDatos;
    private javax.swing.JToolBar herramientas3;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelSuper;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables
}
