/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import java.awt.BorderLayout;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Arrays;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import poo.pl2.Particular;
import poo.pl2.TarjetaCredito;
import poo.pl2.UtilUsuarios;

public class InicioParticular extends javax.swing.JFrame {

    /**
     * Creates new form InicioParticular
     */
    public InicioParticular() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        buscarInmuebles = new javax.swing.JButton();
        consultarReservas = new javax.swing.JButton();
        modDatos = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelPrincipal = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jToolBar1.setRollover(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(24, 40, 134));
        jLabel1.setText("PARTICULAR");
        jToolBar1.add(jLabel1);

        buscarInmuebles.setIcon(new javax.swing.ImageIcon("C:\\Users\\Esthe\\OneDrive - Universidad de Alcala\\GISI\\1curso\\Programación\\PL2\\imagenes\\busquedaPequeña.png")); // NOI18N
        buscarInmuebles.setToolTipText("Buscar Inmuebles");
        buscarInmuebles.setFocusable(false);
        buscarInmuebles.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buscarInmuebles.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buscarInmuebles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarInmueblesActionPerformed(evt);
            }
        });
        jToolBar1.add(buscarInmuebles);

        consultarReservas.setIcon(new javax.swing.ImageIcon("C:\\Users\\Esthe\\OneDrive - Universidad de Alcala\\GISI\\1curso\\Programación\\PL2\\imagenes\\reservaPequeña.png")); // NOI18N
        consultarReservas.setToolTipText("Consulta Reservas");
        consultarReservas.setFocusable(false);
        consultarReservas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        consultarReservas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        consultarReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarReservasActionPerformed(evt);
            }
        });
        jToolBar1.add(consultarReservas);

        modDatos.setIcon(new javax.swing.ImageIcon("C:\\Users\\Esthe\\OneDrive - Universidad de Alcala\\GISI\\1curso\\Programación\\PL2\\imagenes\\usuarioPequeño.png")); // NOI18N
        modDatos.setToolTipText("Modificación Datos Personales");
        modDatos.setFocusable(false);
        modDatos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        modDatos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        modDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modDatosActionPerformed(evt);
            }
        });
        jToolBar1.add(modDatos);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Esthe\\OneDrive - Universidad de Alcala\\GISI\\1curso\\Programación\\PL2\\imagenes\\LogoPequeño.png")); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Esthe\\OneDrive - Universidad de Alcala\\GISI\\1curso\\Programación\\PL2\\imagenes\\LogoJavaBnB.png")); // NOI18N

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(jLabel10)
                .addContainerGap(1361, Short.MAX_VALUE))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jLabel10)
                .addContainerGap(609, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(panelPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(218, 218, 218)
                        .addComponent(jLabel9)
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void modDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modDatosActionPerformed
        // TODO add your handling code here:
        DatosPartic datosPartic = new DatosPartic();
        datosPartic.setSize(400,310);
        datosPartic.setLocation(0,0);
        
        Particular particular = UtilUsuarios.getPartic();
        
        datosPartic.setFieldNombre(particular.getNombre());
        datosPartic.setFieldDni(particular.getDni());
        datosPartic.setFieldTelefono(particular.getTelefono());
        datosPartic.setFieldCorreo(particular.getCorreoElectronico());
        datosPartic.setFieldClave(particular.getClave());
        TarjetaCredito tc = particular.getTarjetaCredito();
        datosPartic.setFechaCaducidad(tc.getFechaCaducidad());
        datosPartic.setFieldNumeroTarjeta(tc.getNumero());
        
        JButton buttonGuardar = new JButton("Guardar");
        buttonGuardar.setBounds(80, 385, 105, 35);
        
        panelPrincipal.removeAll();
        panelPrincipal.setLayout(new BorderLayout());
        panelPrincipal.add(datosPartic, BorderLayout.CENTER);
        panelPrincipal.add(buttonGuardar,BorderLayout.SOUTH);
        panelPrincipal.revalidate();
        panelPrincipal.repaint();
        System.out.println(Arrays.toString(panelPrincipal.getComponents()));
        
        buttonGuardar.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            try{
            String nombre = datosPartic.getFieldNombre();
            String dni = datosPartic.getFieldDni();
            String telefono = datosPartic.getFieldTelefono();
            String correo = datosPartic.getFieldCorreo();
            String clave = datosPartic.getFieldClave();
            
            Date fechaCaducidad = datosPartic.getFechaCaducidad();
            String numero = datosPartic.getFieldNumeroTarjeta();

            Particular partic = UtilUsuarios.getPartic();

            if(UtilUsuarios.modificarDatosParticular(nombre, dni, telefono, correo, clave, numero, fechaCaducidad, partic)){
                JOptionPane.showMessageDialog(buttonGuardar, "Datos modificados.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                datosPartic.borrar();
            } else {
                JOptionPane.showMessageDialog(panelPrincipal, "Error al modificar datos. Compruebe que los datos no son los mismos.", "Mensaje", JOptionPane.ERROR_MESSAGE);
            }
        }catch (HeadlessException exc) {
            JOptionPane.showMessageDialog(panelPrincipal, "Excepción al modificar datos.", "Mensaje", JOptionPane.ERROR_MESSAGE);
            System.out.println("Error: " + exc.toString());
        }
        catch (NullPointerException exc) {
            JOptionPane.showMessageDialog(panelPrincipal, "Excepción al modificar datos: Alguno de los campos es nulo.", "Mensaje", JOptionPane.ERROR_MESSAGE);
            System.out.println("Error: " + exc.toString());
        }
        }
    });
    }//GEN-LAST:event_modDatosActionPerformed

    private void buscarInmueblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarInmueblesActionPerformed
        // TODO add your handling code here:
        BuscarInmueble panelBi = new BuscarInmueble();
        panelBi.setSize(754,449);
        panelBi.setLocation(0,0);
        
        panelPrincipal.removeAll();
        panelPrincipal.add(panelBi, BorderLayout.CENTER);
        panelPrincipal.revalidate();
        panelPrincipal.repaint();
    }//GEN-LAST:event_buscarInmueblesActionPerformed

    private void consultarReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarReservasActionPerformed
        // TODO add your handling code here:
        panelPrincipal.removeAll();
        panelPrincipal.revalidate();
        panelPrincipal.repaint();
        Particular partic = UtilUsuarios.getPartic();
        ListadoReservas lr = new ListadoReservas(this, true, partic);
    }//GEN-LAST:event_consultarReservasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioParticular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioParticular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioParticular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioParticular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioParticular().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarInmuebles;
    private javax.swing.JButton consultarReservas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton modDatos;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables
}
