
package interfaces;

import java.awt.Frame;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import poo.pl2.Inmueble;
import poo.pl2.Particular;
import poo.pl2.Reserva;
import poo.pl2.UtilReservas;

public class ListadoReservas extends javax.swing.JDialog {

    private DefaultTableModel dtm = new DefaultTableModel();
    ArrayList<Reserva> reservas = new ArrayList<>();
    Frame principal;
    /**
     * Creates new form ListadoReservas 
     * entrada del particular -> reservas de un particular
     * @param parent
     * @param modal
     * @param partic
     */
    
    public ListadoReservas(java.awt.Frame parent, boolean modal, Particular partic){//partic
        super(parent, modal);
        initComponents();
        
        ArrayList<Reserva> reservasPartic = UtilReservas.getReservasParticular(partic);
        reservas = UtilReservas.getReservasXfecha(reservasPartic);
        
        String columnas[] = {"FECHA","IMPORTE","INMUEBLE","CLIENTE","ENTRADA", "SALIDA"};
        dtm.setColumnIdentifiers(columnas);
        jTable1.setModel(dtm);
        
        rellenaTabla(reservas);
        
        this.setVisible(true);
    }
    
    /**
     *entrada del anfitrion, reserva de un inmueble de un anfitrión
     * @param parent
     * @param modal
     * @param inm
     */
    public ListadoReservas(java.awt.Frame parent, boolean modal, Inmueble inm){//anfit
        super(parent, modal);
        initComponents();
        
        ArrayList<Reserva> reservasAnfit = UtilReservas.getReservasInmueble(inm);
        reservas = UtilReservas.getReservasXfecha(reservasAnfit);
        
        String columnas[] = {"FECHA","IMPORTE","INMUEBLE","CLIENTE","ENTRADA", "SALIDA"};
        dtm.setColumnIdentifiers(columnas);
        jTable1.setModel(dtm);
        
        rellenaTabla(reservas);
        
        this.setVisible(true);
    }
    
    /**
     *entrada del administrador
     * @param parent
     * @param modal
     */
    public ListadoReservas(java.awt.Frame parent, boolean modal) {//admin
        super(parent, modal);
        initComponents();
        
        ArrayList<Reserva> reservasTodas = UtilReservas.getReservas();
        reservas = UtilReservas.getReservasXfecha(reservasTodas);
        
        String columnas[] = {"FECHA","IMPORTE","INMUEBLE","CLIENTE","ENTRADA", "SALIDA"};
        dtm.setColumnIdentifiers(columnas);
        jTable1.setModel(dtm); 
        
        rellenaTabla(reservas);
        
        this.setVisible(true);
    }
    
    /**
     *vacía la tabla de filas
     */
    public void limpiaTabla() {
        int filas = dtm.getRowCount();
        for (int i = 0; i < filas; i++) {
            dtm.removeRow(0);
        }
    }
    
    /**
     *rellena la tabla con el arrayList de reservas
     * @param reservas
     */
    public void rellenaTabla(ArrayList<Reserva> reservas){
        limpiaTabla();
        for(Reserva res: reservas){
                dtm.addRow(new Object[]{res.getFechaReserva(), res.getImporte(), res.getInmuebleDatos().getTitulo(), res.getClienteParticular().getCorreoElectronico(), res.getFechaEntrada(), res.getFechaSalida()});
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonVer = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Fecha", "Importe", "Inmueble", "Cliente", "Entrada", "Salida"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        buttonVer.setText("Ver Reserva");
        buttonVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVerActionPerformed(evt);
            }
        });

        jLabel19.setIcon(new javax.swing.ImageIcon("C:\\Users\\Esthe\\OneDrive - Universidad de Alcala\\GISI\\1curso\\Programación\\PL2\\imagenes\\LogoPequeño.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(buttonVer))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(buttonVer)
                .addGap(26, 26, 26))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVerActionPerformed
        // TODO add your handling code here:
        int fila = jTable1.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "No hay reserva seleccionada.", "Mensaje", JOptionPane.ERROR_MESSAGE);
        } else{
            Reserva res = reservas.get(fila);
            ConsultarReserva ci = new ConsultarReserva(principal, true, res);
        }
        System.out.println("Button pulsado");
    }//GEN-LAST:event_buttonVerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListadoReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListadoReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListadoReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListadoReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ListadoReservas dialog = new ListadoReservas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonVer;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
